controllers/GoodController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Goods;
use app\models\GoodsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GoodController implements the CRUD actions for Goods model.
 */
class GoodController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Goods models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GoodsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Goods model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Goods model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Goods();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Goods model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Goods model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Goods model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Goods the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Goods::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;
use app\models\Goods;
use app\models\Category;
use app\models\Pages;
use Yii;
use yii\base\Object;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $category = Category::find()->all();
        $goods = Goods::find()->orderBy('rand()')->all();
        $pages = Pages::find()->all();
        return $this->render('index',['category'=>$category,'goods'=>$goods,'pages'=>$pages]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionOrder()
    {
        $model = new \app\models\OrderForm();

        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('orderFormSubmitted');

            return $this->refresh();
        }


        return $this->render('order', [
            'model' => $model,
        ]);
    }



    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


    public function CartDoIt(){
       
        

        $request = Yii::$app->request;
        $cartAdd=$request->post('cartAdd');
        $cartDel=$request->post('cartDel');

        if ((int)$cartAdd>0)
        {
            $id=$cartAdd;
            $good= Goods::find()->where(['id'=>$id])->one();

            if (!isset($_SESSION['cart']))
            {
                $_SESSION['cart'][]=$good->id;

            }else{
                $cart=$_SESSION['cart'];
                if (!in_array($cartAdd,$cart))
                {
                    $_SESSION['cart'][].=$good->id;
                }
            }

            die();
        }
        if ((int)$cartDel>0)
        {
            if (isset($_SESSION['cart']))
            {
                $cart=$_SESSION['cart'];
                unset($_SESSION['cart'][ array_search($cartDel,$cart)]);
            }

            die();
        }
    }


    public  function  actionCart(){

        $request = Yii::$app->request;
         if($request->isAjax){

                $this->CartDoIt();
               die();
        }
         if (Yii::$app->session->get('cart'))
         {
             $cartGoods=Goods::find()->where(['in','id',Yii::$app->session->get('cart')])->all();
         }else{
             $cartGoods=[];
         }


        return $this->render('cart',['cart'=>$cartGoods]);
    }


}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О НАС';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <div class="row">
        <div class=" col-xs-12 col-md-8  offset-md-2 p-2 border-dark rounded">
            <p>
                Компания <strong>ООО «КВАРЦ Энерджи»</strong> - молодая и активно развивающаяся компания в области поставок теплотехнического оборудования.
            </p>
            <p>
                Мы предлагаем широкий ассортимент запасных частей для горелочных устройств, ведущих мировых производителей представленных в рынке теплоэнергетики России.
            </p>
            <p>
                Мы работаем без посредников, для того чтобы обеспечить лучшие условия для наших партнеров.
                <br>Благодаря грамотно выстроенной логистике, мы поставляем оборудование в любой город России в короткий срок.
            </p>
            <p>
                Профессионализм нашей команды оценили сотни предприятий по всей стране.
                <br>
                <strong>ООО «КВАРЦ Энерджи»</strong> приглашает к сотрудничеству всех заинтересованных лиц.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="main_title mb-0  col-xs-12 col-md-8  offset-md-2 pt-5  pb-0 border-dark rounded">
            <h2 class="text-center"><span>Мы оказываем техническую поддержку оборудованию марок:</span></h2>
        </div>
    </div>

    <div class="row p-0">
        <div class=" col-xs-12 col-md-8  offset-md-2 pb-2 pt-0 border-dark rounded">

            <div class="col-md-4">
                <a href="content/about/Ecoflame.png" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Ecoflame.png);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/Ecostar.png" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Ecostar.png);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/Elco.jpg" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Elco.jpg);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/Girsh.jpg" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Girsh.jpg);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/Hansa.jpg" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Hansa.jpg);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/Logo-Riello.jpg" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Logo-Riello.jpg);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/Weishaupt.png" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Weishaupt.png);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/Wesper.gif" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/Wesper.gif);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/baltur_logo.jpg" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/baltur_logo.jpg);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/dreizler_logo.jpg" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/dreizler_logo.jpg);"></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/oilon-small-385x385.jpg" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/oilon-small-385x385.jpg);background-size:contain "></div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="content/about/saacke.jpg.png" class="img-gal">
                    <div class="single-gallery-image" style="background: url(content/about/saacke.jpg.png);"></div>
                </a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class=" col-xs-12 col-md-8  offset-md-2 p-2 border-dark rounded">
            <h3 class="title_color">Оборудование марки Dungs</h3>
            <p>
                Компания Karl Dungs GmbH &amp; Co. KG производитель газового оборудования основана в 1945 году, как электромонтажное предприятие. С 1970 года приступила к производству топочных автоматов и электромагнитных клапанов.
            </p>
            <p>
                Сегодня компания Karl Dungs GmbH &amp; Co. KG оснащает своим оборудованием большинство горелочных устройств применяемых во всем мире.
            </p>
            <p>
                Компания ООО «Кварц Энерджи» является торговым партнером компании ООО «Карл Дунгс» и обеспечивает продажу и техническую поддержку оборудования марки Dungs.
            </p>
            <p>
            <h3 class="title_color text-left">Сертификат официальный партнёр Dungs</h3>
            <img style='max-height:500px;max-widht:350px' src="/content/about/Dungs-1.jpg" class="image-fluid" alt="Сертификат официальный партнёр Dungs"/>
            </p>
        </div>
    </div>
        <div class="row">
            <div class=" col-xs-12 col-md-8  offset-md-2 p-2 border-dark rounded">
                <h3 class="title_color">Оборудование марки Siemens</h3>
                <p>
                    Компания Siemens AG была основана 1847 году, ее создателем является инженер и ученый — Вернер Сименс. Успех к компании Siemens пришел в 1850 году с изобретением телеграфа. Сегодня Siemens AG - крупнейший немецкий концерн работающий в области электроники, энергетического оборудования, светотехники и медицины.
                </p>
                <p>
                    Большинство горелочных устройств поставляемых в нашу страну, оснащены автоматикой управления фирмы Siemens.
                </p>
                <p>
                    Компания ООО «Кварц Энерджи» является партнером компании Siemens и обеспечивает продажу и техническую поддержку оборудования марки Siemens.
                </p>
                <p>
                <h3 class="title_color text-left">Сертификат официальный партнёр Siemens</h3>
                <img  style='max-height:500px;max-widht:350px' src="/content/about/sertSim.jpg" class="image-fluid" alt="Сертификат официальный партнёр Dungs">
                </p>
            </div>
        </div>

            <div class="row">
                <div class=" col-xs-12 col-md-8  offset-md-2 p-2 border-dark rounded">
                    <h3 class="title_color">Оборудование марки Autoflame</h3>
                    <p>
                        Компания Autoflame была основана в 1968 году, как сервисная компания в области автоматизации, котельного оборудования. Сегодня Autoflame – крупнейший производитель контроллеров, которые управляют процессами сжигания топлива.
                    </p>
                    <p>
                        Компания ООО «Кварц Энерджи» является поставщиком оборудования марки Autoflame и обеспечивает поддержку данного оборудования.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class=" col-xs-12 col-md-8  offset-md-2 p-2 border-dark rounded">
                    <h3 class="title_color">Оборудование марки Suntec</h3>
                    <p>
                        Компания SUNTEC была основана в 1984 году путем поглощения компании Sundstrand которая с 1934 года производила шестеренные насосы для масляных горелок.
                    </p>
                    <p>
                        Сегодня SUNTEC разрабатывает, производит и продает непревзойденный ассортимент шестеренных насосов и аксессуаров.
                    </p>
                    <p>
                        SUNTEC, партнер крупнейших производителей систем отопления (бытовые горелки, промышленные котлы, мобильные отопительные установки и системы отопления для транспортных средств), также предлагает технические решения для всех областей применения с использованием шестеренчатого насоса.
                    </p>
                    <p>
                        Компания ООО «Кварц Энерджи» является поставщиком насосов марки SUNTEC, обеспечивает техническую поддержку.
                    </p>
                </div>
            </div>
        </div>

views/site/cart.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;


$this->title = 'Карзина покупок';
$this->params['breadcrumbs'][] = $this->title;



?>
<section class="cart_area">
    <div class="container ">
        <div class="cart_inner">
            <?php
            if (count($cart)>0) {

                ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Продукт</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Удалить</th>

                    </tr>
                    </thead>
                    <tbody>
                    <?php

                    foreach ($cart

                    as $item){
                    ?>
                    <tr>
                        <td>
                            <div class="media1">
                                <div class="text-left">
                                    <img width="100" height="100"
                                         src="/content/<?= $item->id ?>"
                                         alt=""
                                    />
                                </div>
                                <div class="media-body">
                                    <p><?= $item->title ?></p>
                                </div>
                            </div>
                        </td>
                        <td class="text-center">
                            <h5>По запросу</h5>
                        </td>
                        <td class="text-center">
                            <h5><a href="" onclick="removeFromCart(<?= $item->id ?>)">
                                    <i class="fa fa-close"></i></a>
                            </h5>
                        </td>

                        <?php

                        }
                        ?>

                    </tr>
                    <tr class="out_button_area">
                        <td></td>
                        <td>
                            <div class="checkout_btn_inner">
                                <a class="gray_btn" href="/">Продолжить покупку</a>
                                <a class="main_btn" href="/order">Заказать</a>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <?php
            }else{
                echo  'Карта пуста<br><a class="gray_btn" href="/">Продолжить покупку</a>';
            }
            ?>


            </div>
        </div>
    </div>
</section>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Домой';

use yii\helpers\Url;
?>
<section class="home_banner_area ">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content row">
                <div class="col-lg-12">
                    <a class="main_btn mt-40" href="<?=Url::to(['good/index'])?>">Посмотреть каталог</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->

<!-- Start feature Area -->
<section class="feature-area section_gap_bottom_custom pt-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="main_title">
                    <h2><span>Котегории продукции</span></h2>

                </div>
            </div>
        </div>
        <div class="row">
            <?php foreach ($category as $ct){?>
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="<?=Url::to(['category/index/','CategorySearch[id]'=>$ct->id]);?>" class="title">
                        <img src="<?=$ct->image?>" height="90" width="90"  alt="<?=$ct->name?>">
                        <h3 class="text-center"> Оборудование  <?=$ct->name?> </h3>
                    </a>

                </div>
            </div>
            <?php } ?>

        </div>
    </div>
</section>
<!-- End feature Area -->

<!--================ Feature Product Area =================-->
<section class="feature_product_area section_gap_bottom_custom">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="main_title">
                    <h2><span>Новые продукты</span></h2>
                    <p>Наш ассортимент постоянно пополняется новыми товарами от ведущих производителей</p>
                </div>
            </div>
        </div>

        <div class="row">
            <?php
                $i=0;
                foreach ($goods as $good) {
                    if ($i<3) {
                        ?>

                        <div class="col-lg-4 col-md-6">
                            <div class="single-product border-info">
                                <div class="product-img ">
                                    <img  width="200" height="200" src="/content/<?=$good->id?>" alt="<?=$good->title?>"/>
                                    <div class="p_icon">
                                        <a href="<?=Url::to(['good/view/','id'=>$good->id]);?>">
                                            <i class="ti-eye"></i>
                                        </a>
                                        <a  onclick="addToCart(<?=$good->id?>)">
                                            <i class="ti-shopping-cart"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="product-btm">
                                    <a href="<?=Url::to(['good/view/','id'=>$good->id]);?>" class="d-block">
                                        <h4><?=$good->title?></h4>
                                    </a>
                                    <div class="mt-3">
                                        <span class="mr-4">Цена: <strong>По запросу</strong></span>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php
                    }
                    $i++;
            }
            ?>

        </div>
    </div>
</section>
<!--================ End Feature Product Area =================-->

<!--================ Offer Area =================-->
<section >
    <!--
    <div class="container">
        <div class="row justify-content-center">
            <div class="offset-lg-4 col-lg-6 text-center">
                <div class="offer_content">
                    <h3 class="text-uppercase mb-40">all men’s collection</h3>
                    <h2 class="text-uppercase">50% off</h2>
                    <a href="#" class="main_btn mb-20 mt-5">Discover Now</a>
                    <p>Limited Time Offer</p>
                </div>
            </div>
        </div>
    </div>
    !-->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="carousel slide" id="carousel-765102">
                    <ol class="carousel-indicators">
                        <li data-slide-to="0" data-target="#carousel-765102" class="active">
                        </li>
                        <li data-slide-to="1" data-target="#carousel-765102" >
                        </li>
                        <li data-slide-to="2" data-target="#carousel-765102" >
                        </li>
                        <li data-slide-to="3" data-target="#carousel-765102" >
                        </li>

                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active carousel-item-left carousel-item">
                            <img class="d-block w-100" alt="SIEMENS" src="/img/banner/1.jpg" />

                        </div>
                        <div class="carousel-item carousel-item-next carousel-item-left  carousel-item">
                            <img class="d-block w-100" alt="DUNGS" src="/img/banner/2.jpg" />
                        </div>
                        <div class="carousel-item carousel-item-next carousel-item-left  carousel-item">
                            <img class="d-block w-100" alt="SUNTEC" src="/img/banner/3.jpg" />

                        </div>
                        <div class="carousel-item carousel-item-next carousel-item-left  carousel-item">
                            <img class="d-block w-100" alt="AUTOFLAME" src="/img/banner/4.jpg" />

                        </div>


                </div>
            </div>
        </div>
    </div>
</section>


<section class="inspired_product_area section_gap_bottom_custom pt-3">
    <div class="container pt-5">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="main_title">
                    <h2><span>В топе</span></h2>

                </div>
            </div>
        </div>

        <div class="row">
            <?php

            foreach ($category as $cat) {
                ?>

                <div class="col-lg-3 col-md-6 ">
                    <div class="single-product border border-info">
                        <div class="product-img">
                            <img width="200" height="200" src="<?=$cat->image ?>"
                                 alt="<?= $cat->name ?>"/>
                            <div class="p_icon">
                                <a href="<?=Url::to(['category/index','CategorySearch[id]'=>$cat->id]);?>">
                                    <i class="ti-eye"></i>
                                </a>
                            </div>
                        </div>
                        <div class="product-btm">
                            <a  href="<?=Url::to(['category/index','CategorySearch[id]'=>$cat->id]);?>" class="d-block">

                                <h4>Оборудования <?= $cat->name ?></h4>
                            </a>

                        </div>
                    </div>
                </div>

            <?php    foreach (\app\models\Goods::find()->where(['category_id'=>$cat->id])->orderBy('LENGTH(title),rand()')->limit(3)->all() as $good)
            {

                    ?>
                    <div class="col-lg-3 col-md-6 p-2">
                        <div class="single-product ">
                            <div class="product-img">
                                <img width="150" height="150" src="/content/<?= $good->id ?>"
                                     alt="<?= $good->title ?>"/>
                                <div class="p_icon">
                                    <a href="<?=Url::to(['good/view/','id'=>$good->id]);?>">
                                        <i class="ti-eye"></i>
                                    </a>
                                    <a  onclick="addToCart(<?=$good->id?>)">
                                        <i class="ti-shopping-cart"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="product-btm">
                                <a href="<?=Url::to(['good/view/','id'=>$good->id]);?>" class="d-block">
                                    <h4><?=$good->title?></h4>
                                </a>
                                <div class="mt-3">
                                    <span class="mr-4">Цена: <strong>По запросу</strong></span>

                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                }

            }
            ?>
        </div>
    </div>
</section>
<section class="feature-area section_gap_bottom_custom pt-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="main_title">
                    <h2><span>Наши партнеры</span></h2>

                </div>
            </div>
        </div>
        <div class="row">
            
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="https://мойгазовыйкотел.рф/" target='_blank' class="title">
                        <img src="https://xn--c1aekbfedbmgce6cg8joa.xn--p1ai/static/images/rsa.jpg" alt="мойгазовыйкотел.рф" height="90"  >
                        <h3 class="text-center">Газовые котлы<br>Rossen</h3>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="https://мойугольныйкотел.рф/" target='_blank' class="title">
                        <img  src="https://xn--c1aekbfedbmgce6cg8joa.xn--p1ai/assets/images/16.jpg" alt="https://мойугольныйкотел.рф" height="90" >
                        <h3 class="text-center">Автоматизированные угольные котлы</h3>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="https://котельных-сервис.рф/" target='_blank' class="title">
                        <img  src="https://xn--80aebkijeikbwed0d0h.xn--p1ai/static/img/person.png" alt="https://котельных-сервис.рф" height="90"  >
                        <h3 class="text-center">Обслуживание котельных</h3>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="http://ecostar.ru.com/" target='_blank' class="title">
                        <img  src="http://ecostar.ru.com/Ecostar.jpg" alt="http://ecostar.ru.com/" height="90"  >
                        <h3 class="text-center">Горелки<br>Ecostar</h3>
                    </a>
                </div>
            </div>

            


        </div>
    </div>
</section>

<?php

//начало многосточной строки, можно использовать любые кавычки
$script = <<< JS
        $(function(){
        $('#carousel-765102').carousel({
            interval: 500,
            
        });
    });
JS;
//маркер конца строки, обязательно сразу, без пробелов и табуляции
$this->registerJs($script, yii\web\View::POS_READY);

?>